serial:
  port: 40011 #串口端口

spring:
    application:
        name: os-mina-pushcoin
server:
    port: 40010 #启动端口 40010,40011 .... 40019

eureka:
     instance:
        preferIpAddress: true
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:20010/eureka/

feign:
  okhttp:
    enabled: true
  httpclient:
    max-connections: 200 # 默认值
    max-connections-per-route: 50  # 默认值
  feign:
    hystrix:
      enabled: true   #开启Feign Hystrix 支持
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

